/* sw.js — auto-generated by pipeline/build.py */
const CACHE = "kanji-v7b686a7e";
const PRECACHE = [
  "./",
  "./index.html",
  "./manifest.json",
  "./icons/icon-180.png",
  "./icons/icon-192.png",
  "./icons/icon-512.png",
  "./splash/splash-750x1334.png",
  "./splash/splash-1242x2208.png",
  "./splash/splash-1125x2436.png",
  "./splash/splash-1242x2688.png",
  "./splash/splash-828x1792.png",
  "./splash/splash-1170x2532.png",
  "./splash/splash-1284x2778.png",
  "./splash/splash-1179x2556.png",
  "./splash/splash-1290x2796.png",
];
const FONT_CACHE = "kanji-fonts";

self.addEventListener("install", e => {
  e.waitUntil(
    caches.open(CACHE)
      .then(c => c.addAll(PRECACHE))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", e => {
  e.waitUntil(
    caches.keys().then(keys =>
      Promise.all(
        keys.filter(k => k !== CACHE && k !== FONT_CACHE).map(k => caches.delete(k))
      )
    ).then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", e => {
  const url = new URL(e.request.url);

  // Font requests: cache-first, long-lived separate cache
  if (url.hostname.endsWith("googleapis.com") || url.hostname.endsWith("gstatic.com")) {
    e.respondWith(
      caches.open(FONT_CACHE).then(c =>
        c.match(e.request).then(cached => {
          if (cached) return cached;
          return fetch(e.request).then(res => { c.put(e.request, res.clone()); return res; });
        })
      )
    );
    return;
  }

  // Everything else: cache-first (our own assets)
  e.respondWith(
    caches.match(e.request).then(cached => cached || fetch(e.request))
  );
});
