#!/usr/bin/env node
/**
 * Generate Kanjido app icons + PWA splash screens from branding/kanjido-icon.svg.
 *
 * Run:    npm run icons
 * Output: public/icons/icon-{180,192,512,1024}.png  +  public/icons/icon-512-maskable.png
 *
 * The SVG master is the source of truth — re-run this whenever the master changes.
 *
 * For App Store submission you'll want a designer-rendered master at 1024×1024
 * (Apple's marketing icon size). This pipeline is good enough for Vercel PWA
 * + dev builds.
 */
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import sharp from "sharp";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..");
const SRC_SVG = join(ROOT, "branding/kanjido-icon.svg");
const OUT_DIR = join(ROOT, "public/icons");

/** Standard iOS + Android + PWA sizes. */
const SIZES = [
  { name: "icon-180.png", size: 180 }, // apple-touch-icon
  { name: "icon-192.png", size: 192 }, // PWA "any"
  { name: "icon-512.png", size: 512 }, // PWA "any" / install banner
  { name: "icon-1024.png", size: 1024 }, // App Store marketing icon
];

/**
 * Maskable icons need a 20% safe-zone padding so the device's mask doesn't clip
 * the kanji. We render the SVG at 60% inside the 512×512 frame.
 */
async function renderMaskable(svgBuffer, outPath) {
  const inner = await sharp(svgBuffer).resize(360, 360).png().toBuffer();
  await sharp({
    create: {
      width: 512,
      height: 512,
      channels: 4,
      background: { r: 9, g: 9, b: 11, alpha: 1 },
    },
  })
    .composite([{ input: inner, top: 76, left: 76 }])
    .png()
    .toFile(outPath);
}

async function main() {
  await mkdir(OUT_DIR, { recursive: true });

  const svgBuffer = await import("node:fs").then((fs) => fs.promises.readFile(SRC_SVG));

  for (const { name, size } of SIZES) {
    const outPath = join(OUT_DIR, name);
    await sharp(svgBuffer).resize(size, size).png().toFile(outPath);
    console.log(`  ${name}  ${size}×${size}`);
  }

  await renderMaskable(svgBuffer, join(OUT_DIR, "icon-512-maskable.png"));
  console.log(`  icon-512-maskable.png  512×512 (with 20% safe-zone)`);

  // favicon (.ico is overkill — modern browsers prefer .png; index.html links to icon-192.png)
  await sharp(svgBuffer).resize(32, 32).png().toFile(join(OUT_DIR, "favicon-32.png"));
  console.log(`  favicon-32.png  32×32`);

  // README pointer
  const readme = `# Kanjido app icons

Auto-generated by \`scripts/generate-icons.mjs\` from \`branding/kanjido-icon.svg\`.
Run \`npm run icons\` to regenerate.

For App Store submission, replace the SVG master with a designer-rendered
1024×1024 master and re-run the script.
`;
  await writeFile(join(OUT_DIR, "README.md"), readme);

  console.log("\n✓ Icons regenerated.");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
