"""
extra_kanji_data.py — Hand-curated additional high-frequency kanji NOT in
the existing JLPT N5–N1 decks. These are common kanji an N3+ learner sees
constantly in news, conversation, signage, and real reading material.

Each entry follows the standard kanji card schema:
  kanji, meanings[], on_yomi[], kun_yomi[], keyword, etymology,
  stroke_count, jlpt, grade, examples[{kanji, kana, meaning}]

Sourced from KANJIDIC2 / Jisho / Tofugu cross-checks. Etymology is anchored
in actual radical composition where the etymology is well-known; flagged as
a composition mnemonic where it isn't.
"""

EXTRA_KANJI = [
    {
        "kanji": "京",
        "meanings": ["capital"],
        "on_yomi": ["キョウ", "ケイ"],
        "kun_yomi": [],
        "keyword": "capital",
        "etymology": "Originally a pictograph of a tall building on a hill — the king's palace, the capital.",
        "stroke_count": 8, "jlpt": "N4", "grade": 2,
        "examples": [
            {"kanji": "東京", "kana": "とうきょう", "meaning": "Tokyo (eastern capital)"},
            {"kanji": "京都", "kana": "きょうと", "meaning": "Kyoto (capital city)"},
            {"kanji": "上京", "kana": "じょうきょう", "meaning": "going up to the capital"},
        ],
    },
    {
        "kanji": "成",
        "meanings": ["become", "achieve", "succeed"],
        "on_yomi": ["セイ", "ジョウ"],
        "kun_yomi": ["な(る)"],
        "keyword": "become",
        "etymology": "Halberd (戈) + a mark of completion — the moment a battle is finished, something is achieved.",
        "stroke_count": 6, "jlpt": "N3", "grade": 4,
        "examples": [
            {"kanji": "成功", "kana": "せいこう", "meaning": "success"},
            {"kanji": "成長", "kana": "せいちょう", "meaning": "growth"},
            {"kanji": "完成", "kana": "かんせい", "meaning": "completion"},
        ],
    },
    {
        "kanji": "計",
        "meanings": ["plan", "measure", "count"],
        "on_yomi": ["ケイ"],
        "kun_yomi": ["はか(る)"],
        "keyword": "plan",
        "etymology": "Words (言) + ten (十) — counting up with words, planning.",
        "stroke_count": 9, "jlpt": "N3", "grade": 2,
        "examples": [
            {"kanji": "計画", "kana": "けいかく", "meaning": "plan"},
            {"kanji": "時計", "kana": "とけい", "meaning": "clock"},
            {"kanji": "合計", "kana": "ごうけい", "meaning": "total"},
        ],
    },
    {
        "kanji": "設",
        "meanings": ["establish", "set up", "install"],
        "on_yomi": ["セツ"],
        "kun_yomi": ["もう(ける)"],
        "keyword": "establish",
        "etymology": "Words (言) + an action (殳) — declaring something into being, setting up.",
        "stroke_count": 11, "jlpt": "N3", "grade": 5,
        "examples": [
            {"kanji": "設置", "kana": "せっち", "meaning": "installation, set up"},
            {"kanji": "建設", "kana": "けんせつ", "meaning": "construction"},
            {"kanji": "施設", "kana": "しせつ", "meaning": "facility"},
        ],
    },
    {
        "kanji": "観",
        "meanings": ["view", "observe", "appearance"],
        "on_yomi": ["カン"],
        "kun_yomi": ["み(る)"],
        "keyword": "view",
        "etymology": "A heron (雚) + see (見) — watching like a still bird, observing.",
        "stroke_count": 18, "jlpt": "N3", "grade": 4,
        "examples": [
            {"kanji": "観光", "kana": "かんこう", "meaning": "sightseeing"},
            {"kanji": "観察", "kana": "かんさつ", "meaning": "observation"},
            {"kanji": "客観的", "kana": "きゃっかんてき", "meaning": "objective"},
        ],
    },
    {
        "kanji": "察",
        "meanings": ["perceive", "guess", "investigate"],
        "on_yomi": ["サツ"],
        "kun_yomi": [],
        "keyword": "perceive",
        "etymology": "Roof (宀) + offering (祭) — looking under the roof to perceive what's there.",
        "stroke_count": 14, "jlpt": "N3", "grade": 4,
        "examples": [
            {"kanji": "観察", "kana": "かんさつ", "meaning": "observation"},
            {"kanji": "警察", "kana": "けいさつ", "meaning": "police"},
            {"kanji": "察する", "kana": "さっする", "meaning": "to perceive, to sense"},
        ],
    },
    {
        "kanji": "選",
        "meanings": ["choose", "select", "elect"],
        "on_yomi": ["セン"],
        "kun_yomi": ["えら(ぶ)"],
        "keyword": "choose",
        "etymology": "Walk (辶) + together (巽) — walking through and picking out.",
        "stroke_count": 15, "jlpt": "N3", "grade": 4,
        "examples": [
            {"kanji": "選ぶ", "kana": "えらぶ", "meaning": "to choose"},
            {"kanji": "選挙", "kana": "せんきょ", "meaning": "election"},
            {"kanji": "選手", "kana": "せんしゅ", "meaning": "athlete (selected player)"},
        ],
    },
    {
        "kanji": "判",
        "meanings": ["judge", "decide", "seal"],
        "on_yomi": ["ハン", "バン"],
        "kun_yomi": [],
        "keyword": "judge",
        "etymology": "Half (半) + knife (刂) — cutting in half, deciding.",
        "stroke_count": 7, "jlpt": "N3", "grade": 5,
        "examples": [
            {"kanji": "判断", "kana": "はんだん", "meaning": "judgement, decision"},
            {"kanji": "裁判", "kana": "さいばん", "meaning": "trial"},
            {"kanji": "評判", "kana": "ひょうばん", "meaning": "reputation"},
        ],
    },
    {
        "kanji": "断",
        "meanings": ["cut off", "decide", "decline"],
        "on_yomi": ["ダン"],
        "kun_yomi": ["ことわ(る)", "た(つ)"],
        "keyword": "cut off",
        "etymology": "Threads (㡭) + axe (斤) — cutting threads with an axe, severing.",
        "stroke_count": 11, "jlpt": "N3", "grade": 5,
        "examples": [
            {"kanji": "判断", "kana": "はんだん", "meaning": "judgement"},
            {"kanji": "断る", "kana": "ことわる", "meaning": "to refuse, to decline"},
            {"kanji": "油断", "kana": "ゆだん", "meaning": "carelessness"},
        ],
    },
    {
        "kanji": "制",
        "meanings": ["system", "regulate", "control"],
        "on_yomi": ["セイ"],
        "kun_yomi": [],
        "keyword": "system",
        "etymology": "A tree (未) + knife (刂) — pruning a tree to control it.",
        "stroke_count": 8, "jlpt": "N3", "grade": 5,
        "examples": [
            {"kanji": "制度", "kana": "せいど", "meaning": "system"},
            {"kanji": "規制", "kana": "きせい", "meaning": "regulation"},
            {"kanji": "強制", "kana": "きょうせい", "meaning": "compulsion"},
        ],
    },
    {
        "kanji": "限",
        "meanings": ["limit"],
        "on_yomi": ["ゲン"],
        "kun_yomi": ["かぎ(る)"],
        "keyword": "limit",
        "etymology": "Hill (阝) + stop/glance back (艮) — a hill that stops you, a limit.",
        "stroke_count": 9, "jlpt": "N3", "grade": 5,
        "examples": [
            {"kanji": "制限", "kana": "せいげん", "meaning": "limit, restriction"},
            {"kanji": "限界", "kana": "げんかい", "meaning": "limit, boundary"},
            {"kanji": "期限", "kana": "きげん", "meaning": "deadline"},
        ],
    },
    {
        "kanji": "確",
        "meanings": ["certain", "definite"],
        "on_yomi": ["カク"],
        "kun_yomi": ["たし(か)"],
        "keyword": "certain",
        "etymology": "Stone (石) + crane (鶴 abbr.) — solid as stone, certain.",
        "stroke_count": 15, "jlpt": "N3", "grade": 5,
        "examples": [
            {"kanji": "確認", "kana": "かくにん", "meaning": "confirmation"},
            {"kanji": "正確", "kana": "せいかく", "meaning": "accurate"},
            {"kanji": "確かに", "kana": "たしかに", "meaning": "certainly, indeed"},
        ],
    },
    {
        "kanji": "認",
        "meanings": ["recognize", "approve", "admit"],
        "on_yomi": ["ニン"],
        "kun_yomi": ["みと(める)"],
        "keyword": "recognize",
        "etymology": "Words (言) + endure (忍) — words spoken with patience, formal recognition.",
        "stroke_count": 14, "jlpt": "N3", "grade": 6,
        "examples": [
            {"kanji": "確認", "kana": "かくにん", "meaning": "confirmation"},
            {"kanji": "認める", "kana": "みとめる", "meaning": "to recognize, to approve"},
            {"kanji": "承認", "kana": "しょうにん", "meaning": "approval"},
        ],
    },
    {
        "kanji": "証",
        "meanings": ["proof", "evidence", "certificate"],
        "on_yomi": ["ショウ"],
        "kun_yomi": [],
        "keyword": "proof",
        "etymology": "Words (言) + correct (正) — correct words, sworn testimony.",
        "stroke_count": 12, "jlpt": "N3", "grade": 5,
        "examples": [
            {"kanji": "証明", "kana": "しょうめい", "meaning": "proof, certification"},
            {"kanji": "保証", "kana": "ほしょう", "meaning": "guarantee"},
            {"kanji": "学生証", "kana": "がくせいしょう", "meaning": "student ID"},
        ],
    },
    {
        "kanji": "情",
        "meanings": ["feeling", "emotion", "circumstances"],
        "on_yomi": ["ジョウ"],
        "kun_yomi": ["なさ(け)"],
        "keyword": "feeling",
        "etymology": "Heart (忄) + blue/young (青) — fresh feelings of the heart.",
        "stroke_count": 11, "jlpt": "N3", "grade": 5,
        "examples": [
            {"kanji": "情報", "kana": "じょうほう", "meaning": "information"},
            {"kanji": "感情", "kana": "かんじょう", "meaning": "emotion"},
            {"kanji": "事情", "kana": "じじょう", "meaning": "circumstances"},
        ],
    },
    {
        "kanji": "報",
        "meanings": ["report", "news", "reward"],
        "on_yomi": ["ホウ"],
        "kun_yomi": ["むく(いる)"],
        "keyword": "report",
        "etymology": "A captive (幸) + a hand (又) — handing back, returning information.",
        "stroke_count": 12, "jlpt": "N3", "grade": 5,
        "examples": [
            {"kanji": "情報", "kana": "じょうほう", "meaning": "information"},
            {"kanji": "報告", "kana": "ほうこく", "meaning": "report"},
            {"kanji": "予報", "kana": "よほう", "meaning": "forecast"},
        ],
    },
    {
        "kanji": "告",
        "meanings": ["announce", "tell"],
        "on_yomi": ["コク"],
        "kun_yomi": ["つ(げる)"],
        "keyword": "announce",
        "etymology": "Cow (牛) + mouth (口) — announcing as loud as a bellowing cow.",
        "stroke_count": 7, "jlpt": "N3", "grade": 5,
        "examples": [
            {"kanji": "報告", "kana": "ほうこく", "meaning": "report"},
            {"kanji": "広告", "kana": "こうこく", "meaning": "advertisement"},
            {"kanji": "告白", "kana": "こくはく", "meaning": "confession"},
        ],
    },
    {
        "kanji": "係",
        "meanings": ["relate", "person in charge"],
        "on_yomi": ["ケイ"],
        "kun_yomi": ["かか(る)", "かかり"],
        "keyword": "relate",
        "etymology": "Person (亻) + connect (系) — a person who connects, a person in charge.",
        "stroke_count": 9, "jlpt": "N3", "grade": 3,
        "examples": [
            {"kanji": "関係", "kana": "かんけい", "meaning": "relationship"},
            {"kanji": "係員", "kana": "かかりいん", "meaning": "person in charge"},
            {"kanji": "係長", "kana": "かかりちょう", "meaning": "section chief"},
        ],
    },
    {
        "kanji": "務",
        "meanings": ["duty", "task", "service"],
        "on_yomi": ["ム"],
        "kun_yomi": ["つと(める)"],
        "keyword": "duty",
        "etymology": "Spear (矛) + striking (攵) + power (力) — pushing forward through duty.",
        "stroke_count": 11, "jlpt": "N3", "grade": 5,
        "examples": [
            {"kanji": "義務", "kana": "ぎむ", "meaning": "duty, obligation"},
            {"kanji": "事務", "kana": "じむ", "meaning": "office work"},
            {"kanji": "業務", "kana": "ぎょうむ", "meaning": "business operations"},
        ],
    },
    {
        "kanji": "労",
        "meanings": ["labor", "toil", "trouble"],
        "on_yomi": ["ロウ"],
        "kun_yomi": [],
        "keyword": "labor",
        "etymology": "Fire (火 reduced) + power (力) — work done by sweat and effort.",
        "stroke_count": 7, "jlpt": "N3", "grade": 4,
        "examples": [
            {"kanji": "労働", "kana": "ろうどう", "meaning": "labor"},
            {"kanji": "苦労", "kana": "くろう", "meaning": "hardship"},
            {"kanji": "疲労", "kana": "ひろう", "meaning": "fatigue"},
        ],
    },
    {
        "kanji": "良",
        "meanings": ["good"],
        "on_yomi": ["リョウ"],
        "kun_yomi": ["よ(い)"],
        "keyword": "good",
        "etymology": "A pictograph of clean grain — the good grain selected from chaff.",
        "stroke_count": 7, "jlpt": "N3", "grade": 4,
        "examples": [
            {"kanji": "良い", "kana": "よい", "meaning": "good"},
            {"kanji": "改良", "kana": "かいりょう", "meaning": "improvement"},
            {"kanji": "良心", "kana": "りょうしん", "meaning": "conscience"},
        ],
    },
    {
        "kanji": "建",
        "meanings": ["build", "erect"],
        "on_yomi": ["ケン"],
        "kun_yomi": ["た(てる)", "た(つ)"],
        "keyword": "build",
        "etymology": "A brush (聿) + step forward (廴) — drawing a plan and stepping forward to build.",
        "stroke_count": 9, "jlpt": "N3", "grade": 4,
        "examples": [
            {"kanji": "建てる", "kana": "たてる", "meaning": "to build"},
            {"kanji": "建物", "kana": "たてもの", "meaning": "building"},
            {"kanji": "建設", "kana": "けんせつ", "meaning": "construction"},
        ],
    },
    {
        "kanji": "備",
        "meanings": ["prepare", "equip"],
        "on_yomi": ["ビ"],
        "kun_yomi": ["そな(える)"],
        "keyword": "prepare",
        "etymology": "Person (亻) + arrows-in-quiver (備 right) — a person stocked with arrows, prepared.",
        "stroke_count": 12, "jlpt": "N3", "grade": 5,
        "examples": [
            {"kanji": "準備", "kana": "じゅんび", "meaning": "preparation"},
            {"kanji": "備える", "kana": "そなえる", "meaning": "to prepare for, to equip"},
            {"kanji": "設備", "kana": "せつび", "meaning": "facilities, equipment"},
        ],
    },
    {
        "kanji": "委",
        "meanings": ["entrust", "committee"],
        "on_yomi": ["イ"],
        "kun_yomi": ["ゆだ(ねる)"],
        "keyword": "entrust",
        "etymology": "Grain (禾) + woman (女) — entrusting the harvest to careful hands.",
        "stroke_count": 8, "jlpt": "N3", "grade": 3,
        "examples": [
            {"kanji": "委員", "kana": "いいん", "meaning": "committee member"},
            {"kanji": "委員会", "kana": "いいんかい", "meaning": "committee"},
            {"kanji": "委託", "kana": "いたく", "meaning": "consignment"},
        ],
    },
    {
        "kanji": "則",
        "meanings": ["rule", "follow"],
        "on_yomi": ["ソク"],
        "kun_yomi": [],
        "keyword": "rule",
        "etymology": "Shell/money (貝) + knife (刂) — the principles of cutting, the rules.",
        "stroke_count": 9, "jlpt": "N3", "grade": 5,
        "examples": [
            {"kanji": "規則", "kana": "きそく", "meaning": "rule, regulation"},
            {"kanji": "原則", "kana": "げんそく", "meaning": "principle"},
            {"kanji": "法則", "kana": "ほうそく", "meaning": "law (scientific)"},
        ],
    },
    {
        "kanji": "条",
        "meanings": ["article", "clause", "stripe"],
        "on_yomi": ["ジョウ"],
        "kun_yomi": [],
        "keyword": "article",
        "etymology": "Person (亻) bent + tree (木) — a thin branch, by extension a clause/article.",
        "stroke_count": 7, "jlpt": "N3", "grade": 5,
        "examples": [
            {"kanji": "条件", "kana": "じょうけん", "meaning": "condition"},
            {"kanji": "条約", "kana": "じょうやく", "meaning": "treaty"},
            {"kanji": "一条", "kana": "いちじょう", "meaning": "one (article/streak)"},
        ],
    },
    {
        "kanji": "件",
        "meanings": ["case", "matter", "counter"],
        "on_yomi": ["ケン"],
        "kun_yomi": [],
        "keyword": "case",
        "etymology": "Person (亻) + cow (牛) — a person and a cow, a matter or case.",
        "stroke_count": 6, "jlpt": "N3", "grade": 5,
        "examples": [
            {"kanji": "事件", "kana": "じけん", "meaning": "incident, case"},
            {"kanji": "条件", "kana": "じょうけん", "meaning": "condition"},
            {"kanji": "用件", "kana": "ようけん", "meaning": "matter (of business)"},
        ],
    },
    {
        "kanji": "修",
        "meanings": ["mend", "study", "discipline"],
        "on_yomi": ["シュウ"],
        "kun_yomi": ["おさ(める)"],
        "keyword": "mend",
        "etymology": "Person + hairs (修 left) + 彡 fine lines — refining, polishing oneself.",
        "stroke_count": 10, "jlpt": "N3", "grade": 5,
        "examples": [
            {"kanji": "修理", "kana": "しゅうり", "meaning": "repair"},
            {"kanji": "修正", "kana": "しゅうせい", "meaning": "correction, revision"},
            {"kanji": "研修", "kana": "けんしゅう", "meaning": "training"},
        ],
    },
    {
        "kanji": "機",
        "meanings": ["machine", "occasion", "loom"],
        "on_yomi": ["キ"],
        "kun_yomi": ["はた"],
        "keyword": "machine",
        "etymology": "Tree (木) + a small mechanism (幾) — a wooden machine, originally a loom.",
        "stroke_count": 16, "jlpt": "N3", "grade": 4,
        "examples": [
            {"kanji": "機械", "kana": "きかい", "meaning": "machine"},
            {"kanji": "機会", "kana": "きかい", "meaning": "opportunity (homophone with 機械!)"},
            {"kanji": "飛行機", "kana": "ひこうき", "meaning": "airplane"},
        ],
    },
    {
        "kanji": "械",
        "meanings": ["mechanism", "machine"],
        "on_yomi": ["カイ"],
        "kun_yomi": [],
        "keyword": "mechanism",
        "etymology": "Tree (木) + warning (戒) — a wooden device that warns or restrains.",
        "stroke_count": 11, "jlpt": "N3", "grade": 4,
        "examples": [
            {"kanji": "機械", "kana": "きかい", "meaning": "machine"},
            {"kanji": "器械", "kana": "きかい", "meaning": "instrument, apparatus"},
        ],
    },
    {
        "kanji": "工",
        "meanings": ["craft", "work", "construction"],
        "on_yomi": ["コウ", "ク"],
        "kun_yomi": [],
        "keyword": "craft",
        "etymology": "A pictograph of a carpenter's square — a tool for craft.",
        "stroke_count": 3, "jlpt": "N3", "grade": 2,
        "examples": [
            {"kanji": "工場", "kana": "こうじょう", "meaning": "factory"},
            {"kanji": "工事", "kana": "こうじ", "meaning": "construction"},
            {"kanji": "大工", "kana": "だいく", "meaning": "carpenter"},
        ],
    },
    {
        "kanji": "業",
        "meanings": ["business", "industry", "achievement"],
        "on_yomi": ["ギョウ", "ゴウ"],
        "kun_yomi": ["わざ"],
        "keyword": "business",
        "etymology": "A musical instrument frame — by extension, a craft, a business.",
        "stroke_count": 13, "jlpt": "N4", "grade": 3,
        "examples": [
            {"kanji": "工業", "kana": "こうぎょう", "meaning": "industry"},
            {"kanji": "業界", "kana": "ぎょうかい", "meaning": "industry world"},
            {"kanji": "卒業", "kana": "そつぎょう", "meaning": "graduation"},
        ],
    },
    {
        "kanji": "産",
        "meanings": ["produce", "give birth", "property"],
        "on_yomi": ["サン"],
        "kun_yomi": ["う(む)"],
        "keyword": "produce",
        "etymology": "A standing form (立) + life (生 reduced) — bringing life to a stand, producing.",
        "stroke_count": 11, "jlpt": "N3", "grade": 4,
        "examples": [
            {"kanji": "生産", "kana": "せいさん", "meaning": "production"},
            {"kanji": "産業", "kana": "さんぎょう", "meaning": "industry"},
            {"kanji": "出産", "kana": "しゅっさん", "meaning": "childbirth"},
        ],
    },
    {
        "kanji": "農",
        "meanings": ["agriculture", "farming"],
        "on_yomi": ["ノウ"],
        "kun_yomi": [],
        "keyword": "agriculture",
        "etymology": "A song/farm (曲) + agriculture root — working the soil to a rhythm.",
        "stroke_count": 13, "jlpt": "N3", "grade": 3,
        "examples": [
            {"kanji": "農業", "kana": "のうぎょう", "meaning": "agriculture"},
            {"kanji": "農家", "kana": "のうか", "meaning": "farmer/farm household"},
            {"kanji": "農村", "kana": "のうそん", "meaning": "farming village"},
        ],
    },
    {
        "kanji": "輸",
        "meanings": ["transport", "send"],
        "on_yomi": ["ユ"],
        "kun_yomi": [],
        "keyword": "transport",
        "etymology": "Vehicle (車) + a passing element — transporting by vehicle.",
        "stroke_count": 16, "jlpt": "N3", "grade": 5,
        "examples": [
            {"kanji": "輸出", "kana": "ゆしゅつ", "meaning": "export"},
            {"kanji": "輸入", "kana": "ゆにゅう", "meaning": "import"},
            {"kanji": "輸送", "kana": "ゆそう", "meaning": "transportation"},
        ],
    },
    {
        "kanji": "貸",
        "meanings": ["lend", "rent out"],
        "on_yomi": ["タイ"],
        "kun_yomi": ["か(す)"],
        "keyword": "lend",
        "etymology": "Substitute (代) + shell/money (貝) — handing money over, lending.",
        "stroke_count": 12, "jlpt": "N3", "grade": 5,
        "examples": [
            {"kanji": "貸す", "kana": "かす", "meaning": "to lend"},
            {"kanji": "賃貸", "kana": "ちんたい", "meaning": "rental, lease"},
            {"kanji": "貸し出し", "kana": "かしだし", "meaning": "lending, loan"},
        ],
    },
    {
        "kanji": "賃",
        "meanings": ["wages", "rent", "fare"],
        "on_yomi": ["チン"],
        "kun_yomi": [],
        "keyword": "rent",
        "etymology": "Trust (任) + shell/money (貝) — money given in trust, wages or rent.",
        "stroke_count": 13, "jlpt": "N3", "grade": 6,
        "examples": [
            {"kanji": "家賃", "kana": "やちん", "meaning": "rent"},
            {"kanji": "運賃", "kana": "うんちん", "meaning": "fare"},
            {"kanji": "賃金", "kana": "ちんぎん", "meaning": "wages"},
        ],
    },
    {
        "kanji": "預",
        "meanings": ["deposit", "entrust"],
        "on_yomi": ["ヨ"],
        "kun_yomi": ["あず(ける)", "あず(かる)"],
        "keyword": "deposit",
        "etymology": "Beforehand (予) + head (頁) — placing something with one's head bowed in trust.",
        "stroke_count": 13, "jlpt": "N3", "grade": 6,
        "examples": [
            {"kanji": "預ける", "kana": "あずける", "meaning": "to deposit, to entrust"},
            {"kanji": "預金", "kana": "よきん", "meaning": "deposit (money)"},
            {"kanji": "預かる", "kana": "あずかる", "meaning": "to keep, to take charge of"},
        ],
    },
    {
        "kanji": "銀",
        "meanings": ["silver"],
        "on_yomi": ["ギン"],
        "kun_yomi": [],
        "keyword": "silver",
        "etymology": "Metal (金) + halt/glance (艮) — the metal you stop to admire.",
        "stroke_count": 14, "jlpt": "N4", "grade": 3,
        "examples": [
            {"kanji": "銀行", "kana": "ぎんこう", "meaning": "bank"},
            {"kanji": "銀色", "kana": "ぎんいろ", "meaning": "silver color"},
            {"kanji": "銀座", "kana": "ぎんざ", "meaning": "Ginza"},
        ],
    },
    {
        "kanji": "売",
        "meanings": ["sell"],
        "on_yomi": ["バイ"],
        "kun_yomi": ["う(る)"],
        "keyword": "sell",
        "etymology": "An offering (士) + a man (儿) over a roof — selling at a stall.",
        "stroke_count": 7, "jlpt": "N4", "grade": 2,
        "examples": [
            {"kanji": "売る", "kana": "うる", "meaning": "to sell"},
            {"kanji": "売店", "kana": "ばいてん", "meaning": "kiosk, stand"},
            {"kanji": "販売", "kana": "はんばい", "meaning": "sale"},
        ],
    },
    {
        "kanji": "買",
        "meanings": ["buy"],
        "on_yomi": ["バイ"],
        "kun_yomi": ["か(う)"],
        "keyword": "buy",
        "etymology": "Net (罒) + shell/money (貝) — catching what you want with money.",
        "stroke_count": 12, "jlpt": "N5", "grade": 2,
        "examples": [
            {"kanji": "買う", "kana": "かう", "meaning": "to buy"},
            {"kanji": "買い物", "kana": "かいもの", "meaning": "shopping"},
            {"kanji": "売買", "kana": "ばいばい", "meaning": "buying and selling"},
        ],
    },
    {
        "kanji": "客",
        "meanings": ["guest", "customer"],
        "on_yomi": ["キャク", "カク"],
        "kun_yomi": [],
        "keyword": "guest",
        "etymology": "Roof (宀) + each (各) — each visitor under the roof, a guest.",
        "stroke_count": 9, "jlpt": "N4", "grade": 3,
        "examples": [
            {"kanji": "お客様", "kana": "おきゃくさま", "meaning": "honored customer"},
            {"kanji": "観客", "kana": "かんきゃく", "meaning": "audience"},
            {"kanji": "乗客", "kana": "じょうきゃく", "meaning": "passenger"},
        ],
    },
    {
        "kanji": "論",
        "meanings": ["theory", "argument", "discussion"],
        "on_yomi": ["ロン"],
        "kun_yomi": [],
        "keyword": "theory",
        "etymology": "Words (言) + arrange (侖) — arranging words into argument.",
        "stroke_count": 15, "jlpt": "N3", "grade": 6,
        "examples": [
            {"kanji": "議論", "kana": "ぎろん", "meaning": "discussion, argument"},
            {"kanji": "論文", "kana": "ろんぶん", "meaning": "thesis, paper"},
            {"kanji": "理論", "kana": "りろん", "meaning": "theory"},
        ],
    },
    {
        "kanji": "述",
        "meanings": ["state", "describe"],
        "on_yomi": ["ジュツ"],
        "kun_yomi": ["の(べる)"],
        "keyword": "state",
        "etymology": "Walk (辶) + craft/art (朮) — walking through a craft, stating it.",
        "stroke_count": 8, "jlpt": "N3", "grade": 5,
        "examples": [
            {"kanji": "述べる", "kana": "のべる", "meaning": "to state, to describe"},
            {"kanji": "記述", "kana": "きじゅつ", "meaning": "description"},
            {"kanji": "前述", "kana": "ぜんじゅつ", "meaning": "the aforementioned"},
        ],
    },
    {
        "kanji": "材",
        "meanings": ["material", "talent"],
        "on_yomi": ["ザイ"],
        "kun_yomi": [],
        "keyword": "material",
        "etymology": "Tree (木) + ability (才) — a tree of ability, raw material.",
        "stroke_count": 7, "jlpt": "N3", "grade": 4,
        "examples": [
            {"kanji": "材料", "kana": "ざいりょう", "meaning": "ingredients, materials"},
            {"kanji": "木材", "kana": "もくざい", "meaning": "lumber"},
            {"kanji": "人材", "kana": "じんざい", "meaning": "human resources, talented person"},
        ],
    },
    {
        "kanji": "比",
        "meanings": ["compare", "ratio"],
        "on_yomi": ["ヒ"],
        "kun_yomi": ["くら(べる)"],
        "keyword": "compare",
        "etymology": "Two people side by side — comparing.",
        "stroke_count": 4, "jlpt": "N3", "grade": 5,
        "examples": [
            {"kanji": "比べる", "kana": "くらべる", "meaning": "to compare"},
            {"kanji": "比較", "kana": "ひかく", "meaning": "comparison"},
            {"kanji": "比例", "kana": "ひれい", "meaning": "proportion"},
        ],
    },
    {
        "kanji": "較",
        "meanings": ["compare", "contrast"],
        "on_yomi": ["カク", "コウ"],
        "kun_yomi": [],
        "keyword": "compare",
        "etymology": "Vehicle (車) + crossroads (交) — vehicles meeting at a crossroads, compared.",
        "stroke_count": 13, "jlpt": "N2", "grade": 0,
        "examples": [
            {"kanji": "比較", "kana": "ひかく", "meaning": "comparison"},
            {"kanji": "比較的", "kana": "ひかくてき", "meaning": "comparatively"},
        ],
    },
    {
        "kanji": "数",
        "meanings": ["number", "count"],
        "on_yomi": ["スウ"],
        "kun_yomi": ["かず", "かぞ(える)"],
        "keyword": "number",
        "etymology": "A reading + striking (攵) — striking marks to count.",
        "stroke_count": 13, "jlpt": "N4", "grade": 2,
        "examples": [
            {"kanji": "数学", "kana": "すうがく", "meaning": "mathematics"},
            {"kanji": "数える", "kana": "かぞえる", "meaning": "to count"},
            {"kanji": "人数", "kana": "にんずう", "meaning": "number of people"},
        ],
    },
    {
        "kanji": "加",
        "meanings": ["add", "join"],
        "on_yomi": ["カ"],
        "kun_yomi": ["くわ(える)"],
        "keyword": "add",
        "etymology": "Power (力) + mouth (口) — adding voice, joining in.",
        "stroke_count": 5, "jlpt": "N3", "grade": 4,
        "examples": [
            {"kanji": "参加", "kana": "さんか", "meaning": "participation"},
            {"kanji": "加える", "kana": "くわえる", "meaning": "to add"},
            {"kanji": "増加", "kana": "ぞうか", "meaning": "increase"},
        ],
    },
    {
        "kanji": "退",
        "meanings": ["retreat", "leave", "decline"],
        "on_yomi": ["タイ"],
        "kun_yomi": ["しりぞ(く)"],
        "keyword": "retreat",
        "etymology": "Walk (辶) + halt (艮) — walking and stopping, retreating.",
        "stroke_count": 9, "jlpt": "N3", "grade": 6,
        "examples": [
            {"kanji": "退院", "kana": "たいいん", "meaning": "discharge from hospital"},
            {"kanji": "退職", "kana": "たいしょく", "meaning": "retirement"},
            {"kanji": "退屈", "kana": "たいくつ", "meaning": "boredom"},
        ],
    },
    {
        "kanji": "支",
        "meanings": ["support", "branch"],
        "on_yomi": ["シ"],
        "kun_yomi": ["ささ(える)"],
        "keyword": "support",
        "etymology": "A hand (又) holding up something — supporting.",
        "stroke_count": 4, "jlpt": "N3", "grade": 5,
        "examples": [
            {"kanji": "支える", "kana": "ささえる", "meaning": "to support"},
            {"kanji": "支店", "kana": "してん", "meaning": "branch (store)"},
            {"kanji": "支払う", "kana": "しはらう", "meaning": "to pay"},
        ],
    },
    {
        "kanji": "取",
        "meanings": ["take", "obtain"],
        "on_yomi": ["シュ"],
        "kun_yomi": ["と(る)"],
        "keyword": "take",
        "etymology": "Ear (耳) + hand (又) — historically taking ears as battle trophies; broadly, taking.",
        "stroke_count": 8, "jlpt": "N4", "grade": 3,
        "examples": [
            {"kanji": "取る", "kana": "とる", "meaning": "to take"},
            {"kanji": "取材", "kana": "しゅざい", "meaning": "news coverage"},
            {"kanji": "取り消す", "kana": "とりけす", "meaning": "to cancel"},
        ],
    },
    {
        "kanji": "原",
        "meanings": ["origin", "field", "plain"],
        "on_yomi": ["ゲン"],
        "kun_yomi": ["はら"],
        "keyword": "origin",
        "etymology": "Cliff (厂) + spring (泉) — a spring at the foot of a cliff, the origin of water.",
        "stroke_count": 10, "jlpt": "N3", "grade": 2,
        "examples": [
            {"kanji": "原因", "kana": "げんいん", "meaning": "cause"},
            {"kanji": "原料", "kana": "げんりょう", "meaning": "raw material"},
            {"kanji": "高原", "kana": "こうげん", "meaning": "highland, plateau"},
        ],
    },
]
