/**
 * Deck registry — synchronous metadata + lazy-loaded card data.
 *
 * Default deck JSONs (~5 MB raw, ~600 KB gzipped combined) used to be inlined
 * eagerly via `import.meta.glob({ eager: true })`. That blocked first paint
 * with card content the user might never need (free users only see kana +
 * N5; Pro users only browse a few decks per session).
 *
 * Now:
 *   - `DECK_INDEX` (auto-generated by scripts/build-deck-index.mjs) provides
 *     id / name / kind / cardCount / subtitle synchronously. Any UI showing
 *     deck metadata (Home tiles, search placeholders, group lists) reads
 *     from this without pulling card data.
 *   - `loadDeckCards(id)` dynamically imports the matching JSON. Vite emits
 *     each JSON as its own chunk thanks to the per-deck `manualChunks` rule
 *     in vite.config.ts; the service worker precaches them so offline still
 *     works after first online launch.
 *   - A module-level cache prevents the same deck from being re-fetched.
 *   - User-created decks (live in localStorage) bypass this whole pipeline —
 *     `allDecks(state)` slots them in eagerly via `userDecksToDecks`.
 *
 * Use the `useDeckCards(deckId)` hook for the typical "show this deck's
 * cards" pattern; it handles the loading state for you.
 */

import type { AnyCard, Deck, KanjiCard, VocabCard } from "@/types";

import { DECK_INDEX, type DeckIndexEntry } from "./deck-index.generated";

interface RawDeckFile {
  deck_id: string;
  deck_name: string;
  subtitle?: string;
  card_count?: number;
  cards: Array<Record<string, unknown>>;
}

/**
 * Lazy glob: returns `() => Promise<RawDeckFile>` per JSON path. With
 * `eager: false`, Vite emits each as a separate dynamic chunk so we only
 * pay the bytes for decks the user actually opens.
 */
const lazyLoaders = import.meta.glob<{ default: RawDeckFile }>(
  "/agent-files/{kana_,kanji_,vocab_,integrated_}*.json",
);

/** Module-level cache. The Promise (not the resolved value) is cached so
 *  parallel callers share a single import. */
const cardsCache = new Map<string, Promise<AnyCard[]>>();

function fileToPath(file: string): string {
  return `/agent-files/${file}`;
}

function normalizeVocabCard(c: Record<string, unknown>): VocabCard {
  const meanings = (c.meanings as string[] | undefined) ?? [];
  return {
    kanji: (c.word as string) ?? (c.kanji as string) ?? "",
    meanings,
    reading: (c.reading as string) ?? "",
    category: (c.category as string) ?? "",
    context: (c.context as string) ?? "",
    jlpt: (c.jlpt as VocabCard["jlpt"]) ?? undefined,
    example_sentence: (c.example_sentence as string) ?? "",
    example_reading: (c.example_reading as string) ?? "",
    example_meaning: (c.example_meaning as string) ?? "",
    on_yomi: [],
    kun_yomi: [],
    examples: [],
    keyword: meanings[0] ?? "",
    etymology: (c.context as string) ?? "",
    conjugation_table: (c.conjugation_table as VocabCard["conjugation_table"]) ?? undefined,
  };
}

function asKanjiCard(c: Record<string, unknown>): KanjiCard {
  return c as unknown as KanjiCard;
}

/**
 * Default-deck Home order. Lower numbers float to the top. Anything not in
 * the map sorts after these by deck_id.
 */
const ORDER: Record<string, number> = {
  // Kana — beginner gateway
  "kana-hiragana": 10,
  "kana-katakana": 20,

  // Themed vocab (free) — bridges kana to first kanji study
  "vocab-numbers": 30,
  "vocab-time": 40,

  // JLPT progression
  "kanji-jlpt-n5": 100,
  "kanji-jlpt-n4": 110,
  "kanji-jlpt-n3": 120,
  "kanji-jlpt-n2": 130,
  "kanji-jlpt-n1": 140,

  // Frequency tiers
  "kanji-top-100": 200,
  "kanji-top-500": 210,
  "kanji-top-1000": 220,

  // Jōyō by grade
  "kanji-jouyou-grade-1": 300,
  "kanji-jouyou-grade-2": 310,
  "kanji-jouyou-grade-3": 320,
  "kanji-jouyou-grade-4": 330,
  "kanji-jouyou-grade-5": 340,
  "kanji-jouyou-grade-6": 350,
  "kanji-jouyou-secondary": 360,

  // Themed vocab (Pro)
  "vocab-counters": 400,
  "vocab-body": 410,
  "vocab-family": 420,
  "vocab-food": 430,
  "vocab-verbs": 440,
  "vocab-adjectives": 450,
  "vocab-verbs-pairs": 455,
  "vocab-onomatopoeia": 460,
  "vocab-travel": 470,
  "vocab-weather": 480,
  "vocab-office": 490,
  "vocab-restaurant": 491,
  "vocab-medical": 492,
  "vocab-colors": 493,
  "vocab-animals": 494,
  "vocab-emotions": 495,
  "vocab-proverbs": 496,

  // Grammar (Pro)
  "grammar-particles": 500,
  "grammar-patterns": 510,
  "grammar-conjugations": 520,
};

function rank(id: string): number {
  return ORDER[id] ?? 9999;
}

/** Build a metadata-only Deck shell from a generated index entry. */
function shellOf(entry: DeckIndexEntry): Deck {
  return {
    id: entry.id,
    name: entry.name,
    subtitle: entry.subtitle,
    kind: entry.kind,
    available: true,
    cardCount: entry.cardCount,
    cardKeys: entry.cardKeys,
    cards: [],
  };
}

/**
 * Synchronous default deck list with empty `cards: []`. Use `cardCount` for
 * counts; use `loadDeckCards(id)` or the `useDeckCards()` hook for actual
 * card data.
 */
export const DECKS: Deck[] = [...DECK_INDEX]
  .map(shellOf)
  .sort((a, b) => rank(a.id) - rank(b.id) || a.name.localeCompare(b.name));

/**
 * Resolve and parse the cards array for one default deck. Caches the
 * Promise so concurrent callers share work, and so re-renders that
 * trigger this don't re-fetch.
 */
export function loadDeckCards(deckId: string): Promise<AnyCard[]> {
  const cached = cardsCache.get(deckId);
  if (cached) return cached;

  const entry = DECK_INDEX.find((e) => e.id === deckId);
  if (!entry) return Promise.reject(new Error(`Unknown deck: ${deckId}`));
  const path = fileToPath(entry.file);
  const loader = lazyLoaders[path];
  if (!loader) return Promise.reject(new Error(`No loader for deck file: ${path}`));

  const isGrammar = entry.file.startsWith("vocab_grammar_");
  const promise = loader().then((mod) => {
    const raw: RawDeckFile = (mod as unknown as { default?: RawDeckFile }).default ?? (mod as unknown as RawDeckFile);
    if (entry.kind === "vocab" || entry.kind === "grammar" || isGrammar) {
      return raw.cards.map(normalizeVocabCard) as AnyCard[];
    }
    return raw.cards.map(asKanjiCard) as AnyCard[];
  });
  cardsCache.set(deckId, promise);
  return promise;
}

/**
 * Hydrate every default deck. Used by Mixed Review and any other path that
 * needs to iterate cards across all decks at once. Resolved deck-id ↦ cards
 * is returned via Map; the lazy-load cache absorbs the work so subsequent
 * navigations stay instant.
 */
export function preloadAllDefaultDeckCards(): Promise<Map<string, AnyCard[]>> {
  return Promise.all(
    DECK_INDEX.map(async (entry) => [entry.id, await loadDeckCards(entry.id)] as const),
  ).then((pairs) => new Map(pairs));
}

/**
 * Test-only helper: clear the lazy-load cache. Useful in unit tests that
 * exercise the loader path multiple times.
 */
export function _resetDeckCardsCacheForTests(): void {
  cardsCache.clear();
}

/**
 * If the deck has already been loaded into the cache, return its cards
 * synchronously. Otherwise return null. Used by paths (e.g. MixedReview's
 * preview) that want to avoid kicking off a load if the data isn't ready.
 */
export function peekLoadedDeckCards(deckId: string): AnyCard[] | null {
  const cached = cardsCache.get(deckId);
  if (!cached) return null;
  // We can't synchronously unwrap a Promise, but we can stash resolved
  // results in a side cache and check there. Skip the optimization for
  // now — callers that need sync access should use the hook.
  void cached;
  return null;
}
